#!/bin/bash
ip_address='^((25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])\.){3}(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9][0-9]?)$'
action=$1

[[ "$action" != "unban" && "$action" != "ban" ]] && \
echo "$(basename $0): incorrect action.
usage: $(basename $0) ban/unban jail ip"

[[ "$action" == "ban" ]] && action=banip
[[ "$action" == "unban" ]] && action=unbanip
jail=$2
target=$3

if [[ -n "$target" && "$target" =~ $ip_address ]]; then
  sudo fail2ban-client set $jail $action $target
elif [[ -n "$target" && ! ( "$target" =~ $ip_address ) ]]; then
  echo "$(basename $0): incorrect ip input"
elif [[ "$action" == *element && "$jail" =~ $ip_address ]]; then
  echo "$(basename $0): ban/unban requires jail before ip"
elif [[ "$action" == *element && -z "$target" ]]; then
  echo "$(basename $0): ban/unban requires ip"
fi
