#!/bin/bash
. $HOME/zsh_settings/common/cmd_display.sh
action=$1

[[ "$action" != "unban" && "$action" != "ban" && "$action" != "list" && "$action" != "rules" ]] && \
echo "$(basename $0): incorrect action.
usage: $(basename $0) ban set ip (time)
usage: $(basename $0) unban set ip
usage: $(basename $0) list/rules
"

[[ "$action" == "ban" ]] && action="add element"
[[ "$action" == "unban" ]] && action="delete element"
[[ "$action" == "list" ]] && action="list set"
[[ "$action" == "rules" ]] && action="list table"
jail=$2
target=$3
time=$4

if [[ -n "$target" && "$target" =~ $ip_address ]]; then
  if [[ -n "$time" ]] && [[ "$jail" == "whitelist" || "$jail" == "blacklist" ]]; then
    zsh_cmd="sudo nft $action inet filter $jail { $target timeout $time }"
  else
    zsh_cmd="sudo nft $action inet filter $jail { $target }"
  fi
elif [[ -n "$target" && ! ( "$target" =~ $ip_address ) ]]; then
  echo "$(basename $0): incorrect ip input"
elif [[ "$action" == *element && "$jail" =~ $ip_address ]]; then
  echo "$(basename $0): ban/unban requires set before ip"
elif [[ "$action" == *element && -z "$target" ]]; then
  echo "$(basename $0): ban/unban requires ip"
else
  zsh_cmd="sudo nft $action inet filter $jail"
fi

zsh_eval "$zsh_cmd"
