#!/bin/bash
# ip_address='^((25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])\.){3}(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])$'
ip_address='^((25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])\.){3}(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9][0-9]?)$'
action=$1

[[ "$action" != "unban" && "$action" != "ban" && "$action" != "list" && "$action" != "rules" ]] && \
echo "$(basename $0): incorrect action.
usage: $(basename $0) ban/unban/list/rules set ip"

[[ "$action" == "ban" ]] && action="add element"
[[ "$action" == "unban" ]] && action="delete element"
[[ "$action" == "list" ]] && action="list set"
[[ "$action" == "rules" ]] && action="list table"
jail=$2
target=$3

if [[ -n "$target" && "$target" =~ $ip_address ]]; then
  sudo nft $action inet filter $jail \{ $target \}
elif [[ -n "$target" && ! ( "$target" =~ $ip_address ) ]]; then
  echo "$(basename $0): incorrect ip input"
elif [[ "$action" == *element && "$jail" =~ $ip_address ]]; then
  echo "$(basename $0): ban/unban requires set before ip"
elif [[ "$action" == *element && -z "$target" ]]; then
  echo "$(basename $0): ban/unban requires ip"
else
  sudo nft $action inet filter $jail
fi
