#!/bin/bash
. $HOME/zsh_settings/common/cmd_display.sh
#grep -nR $1 = rgrep

[[ -z "$2" ]] && \
zsh_cmd="grep \
--color=auto \
--line-number \
--dereference-recursive "$1" \
" || \
zsh_cmd="grep \
--color=auto \
--line-number \
--dereference-recursive "$1" \
"$2" \
"

zsh_eval "$zsh_cmd"
