#!/bin/bash
source $ZSHREP/common/cmd_display.sh

zsh_cmd="sudo journalctl -u $1 \
| tac \
| grep \
--max-count=1 \
--before-context=10000 \
--regexp='-- Boot' \
| tac \
"
# | grep "$(date '+%b %d')"
zsh_eval "$zsh_cmd"
