#!/bin/bash
os_id=$(grep '^ID=' /etc/os-release | cut -d= -f2)
[[ "$os_id" == "debian" ]] && echo "denied" && exit 1
[[ "$os_id" == "ubuntu" ]] && identity=~/.ssh/id_nuc_server
ssh -L $1:127.0.0.1:$1 -p 2222 -i $identity ryusandorosu@87.117.169.26
