alias unbanip='sudo fail2ban-client set sshd unbanip'
alias banip='sudo fail2ban-client set sshd banip'
alias banlist='sudo fail2ban-client status sshd'
alias banlog='sudo cat /var/log/fail2ban.log'
alias authlog='sudo cat /var/log/auth.log'
alias longban='sudo fail2ban-client set recidive banip'
alias longunban='sudo fail2ban-client set recidive unbanip'
alias longbanlist='sudo fail2ban-client status recidive'
