#!/bin/bash
source $ZSHREP/common/cmd_display.sh
# git ls-files -t: sefi-deprecated option. alternatives: git status --porcelain; git status --short; git diff-files --name-status; git diff-files --name-only; git diff --name-status (less-like)
# flags comparison only, commands are not equal by output format: git status --untracked-files=all == git ls-files -om

gitcmd=(git)
if   [[ -d "$1" ]]; then gitcmd+=(-C "$1");
elif [[ -f "$1" ]]; then gitcmd+=(-C "$(dirname $1)"); fi

zsh_cmd=(
  "${gitcmd[@]}"
  ls-files
  -t
  --full-name
)

zsh_eval "${zsh_cmd[@]}"
