#!/usr/bin/env zsh
source $ZSHREP/fzf/presets/main.sh

gitcmd=(git)

if [[ -z "$1" ]]; then

  preview_bat "{}" git
  bind_exec "$(_get_editor)" "{}"
  bind_fileinfo "{}"

else

  if   [[ -d "$1" ]]; then gitcmd+=(-C "$1");
  elif [[ -f "$1" ]]; then gitcmd+=(-C $(dirname "$1")); fi
  repo_path="$("${gitcmd[@]}" rev-parse --show-toplevel)"

  preview_bat "$repo_path/{}" git
  bind_exec "$(_get_editor)" "$repo_path/{}"
  bind_fileinfo "$repo_path/{}"

fi

gitcmd+=(
  ls-files
  --full-name
)

"${gitcmd[@]}" | \
fzf "${fzfdefaults[@]}" \
    "${previewcmd[@]}" \
    "${briefinfo[@]}" \
    "${bindexec[@]}"
