#!/usr/bin/env zsh
source $ZSHREP/fzf/presets/main.sh

# seems like this is not needed anymore

gitcmd=(git)

if   [[ -d "$1" ]]; then gitcmd+=(-C "$1");
elif [[ -f "$1" ]]; then gitcmd+=(-C $(dirname "$1")); fi
if   [[ -n "$1" ]]; then repo_path="$("${gitcmd[@]}" rev-parse --show-toplevel)/"; fi

preview_bat "${repo_path}{}" git
bind_exec "$(_get_editor)" "${repo_path}{}"
bind_fileinfo "${repo_path}{}"

gitcmd+=(
  ls-files
  --full-name
)

"${gitcmd[@]}" \
| fzf "${fzfdefaults[@]}" \
      "${previewcmd[@]}" \
      "${briefinfo[@]}" \
      "${bindexec[@]}"
