#!/bin/bash
source $ZSHREP/common/fzf/presets.sh
[[ -n "$1" && "$1" == status ]] && shift

if [[ -z "$1" ]]; then

  gitignore=".gitignore"
  [[ -f "$gitignore" ]] && gitignore_arg="-X $gitignore" || gitignore_arg=""

  repo_flag=""

  # preview_bat "{}" git
  preview_git diff "" "{}"
  bind_exec "git add" "{+}"
  bind_fileinfo "{}"

else

  gitignore="$repo_path/.gitignore"
  [[ -f "$gitignore" ]] && gitignore_arg="-X $gitignore" || gitignore_arg=""

  if [[ -d "$1" ]]; then repo_flag="-C $1";
  elif [[ -f "$1" ]]; then repo_flag="-C $(dirname $1)"; fi
  repo_path="$(git -C $1 rev-parse --show-toplevel)"

  # preview_bat "$repo_path/{}" git
  preview_git diff "$repo_path" "$repo_path/{}"
  bind_exec "git -C "$1" add" "$repo_path/{+}"
  bind_fileinfo "$repo_path/{}"

fi

# git status --untracked-files(=all) == git ls-files -om
cmd=(
  git
  $repo_flag
  ls-files
  -om
  $gitignore_arg
)

"${cmd[@]}" | \
fzf "${fzfdefaults[@]}" \
    "${previewcmd[@]}" \
    "${briefinfo[@]}" \
    "${bindexec[@]}" \
    --multi
